name: flutter_openim_widget
description: The public ui library is used with the openim demo, and you can directly use it for secondary development.
version: 2.0.8
homepage: https://github.com/hrxiang/flutter_openim_widget.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0
  rxdart: ^0.27.3
  flutter_screenutil: ^5.3.1
  flutter_slidable: ^1.2.0
#  cached_network_image: ^3.2.0
#  photo_view: ^0.13.0
  path_provider: ^2.0.9
  flutter_image_compress: ^1.1.0
  record: ^3.0.2
  just_audio: ^0.9.20
  lottie: ^1.2.2
  permission_handler: ^9.1.0
  extended_text_field: ^10.0.1
  extended_image: ^6.0.2+1
  focus_detector: ^2.0.1
  sprintf: ^6.0.0
  flutter_inappwebview: ^5.3.2
  animate_do: ^2.1.0
  flutter_svg: ^1.0.3
  qq_badge: ^0.0.2
#  better_player: ^0.0.81
  chewie: ^1.3.1
  video_player: ^2.3.0
  flutter_cache_manager: ^3.3.0
  mime_type: ^1.0.0
  dio: ^4.0.6
  flutter_keyboard_visibility: ^5.2.0
#  flutter_openim_sdk: ^2.0.0+5
  flutter_openim_sdk:
    path: ../flutter_openim_sdk


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
    assets:
      - assets/images/
      - assets/anim/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages


#  flutter packages pub publish --dry-run
#  flutter packages pub publish
#  flutter packages pub publish --server=https://pub.dartlang.org